baseURL = "https://isaisi9.github.io/static_website/"     # Enlace a la entrada
languageCode = "en-es"  			# Idioma
title = "TECNOLOGIA WEB 4.0"  		# Titulo
publishDir = "docs"   				# Creacion de archivos
theme = "ananke"     				# Ruta al tema
#
# Configuración adicional del sitio web
#
# MetaDataFormat         = "yaml" # Formato cabeceras
# DefaultContentLanguage = "es"   # Idioma por defecto del contenido
# SectionPagesMenu       = "main" #
# Paginate               = 3      # Posts por página en main
# googleAnalytics        = ""     # Código para estadísticas web
# enableRobotsTXT        = true   # Buscadores
#
#  Configuración del mapa de la web
#
# [sitemap]
#   changefreq = "monthly"
#   priority   = 0.5
#   filename   = "sitemap.xml"
#   #
#  Configuración de parámetros de la web
#
# [params]
#   favicon     = ""
#   description = "Laboratorio de experimentos de un matemático"
#   facebook    = ""
#   twitter     = "https://twitter.com/GoHugoIO"
#   instagram   = ""
#   youtube     = ""
#   github      = ""
#   linkedin    = ""
#   background_color_class = "bg-black"
#   featured_image         = "/images/gohugo-default-sample-hero-image.jpg"
#   recent_posts_number    = 2
